on: [push]
name: CI

jobs:
  tests:
    name: Tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest

        php:
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "nightly"

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          ini-values: assert.exception=1, zend.assertions=1

      - name: Install composer dependencies
        run: composer update --no-interaction --prefer-dist

      - name: Run unit tests
        run: vendor/bin/phpunit --coverage-text
